version: "3.3"
services:
  spark-master:
    image: dustedduke/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - sparkNet
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
  spark-worker:
    image: dustedduke/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - sparkNet
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"
    volumes:
      - "./:/local"
  hadoop-hdfs:
    image: teivah/hadoop:2.9.2
    container_name: hadoop-hdfs
    hostname: hadoop
    ports:
      - "50070:50070"
      - "9000:9000"
      - "50075:50075"
      - "50010:50010"
    networks:
      - sparkNet
    volumes:
      - "./:/data"
networks:
  sparkNet:
#    driver: bridge
    external: true
#    ipam:
#      driver: default
